services:
  - type: web
    name: podcastfy-backend
    runtime: docker
    buildCommand: ""
    startCommand: ""
    plan: free
    dockerfilePath: ../Dockerfile_api
    dockerContext: ..
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: "False"
      - key: DEFAULT_VOICE
        value: "Rachel"
      - key: LANGUAGE
        value: "en"
      - key: LOG_LEVEL
        value: "INFO"
      - key: PORT
        value: "8000"
